DaliFood.AdminPanel/Pages/Comment/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DaliFood.Utilites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DaliFood.AdminPanel.Pages.Comment
{
    public class IndexModel : PageModel
    {
        readonly UnitOfWork unitofwork;
        public IndexModel(UnitOfWork unitofwork)
        {
            this.unitofwork = unitofwork;
        }
        [BindProperty]
        public IEnumerable<Models.CustomerComment> CustomerComment { get; set; }

        public void OnGet(int? SearchStatus,int? CustomerId, string SearchQ = null, string SearchStartDate = null, string SearchEndDate = null)
        {
            ViewData["CustomerId"] = 
                new SelectList(unitofwork.CustomerRepository.GetAll(), "Id", "Name");

            var customerId = User.Claims.Where(p => p.Type == SD.CustomerId).FirstOrDefault().Value;
            
            if (customerId == SD.AdminCustomerId)
            {
                CustomerComment = unitofwork.CustomerCommentRepository
                .GetAll(orderby: p => p.OrderByDescending(p => p.CreateDate));
                if (CustomerId.HasValue)
                {
                    CustomerComment = unitofwork.CustomerCommentRepository
                   .GetAll(orderby: p => p.OrderByDescending(p => p.CreateDate), where: p => p.CustomerId == CustomerId);
                }
            }
            else
            {
                ViewData["CustomerId"] = new SelectList(unitofwork.CustomerRepository.GetAll(where:p=>p.Id== int.Parse(customerId)), "Id", "Name");

                CustomerComment = unitofwork.CustomerCommentRepository
               .GetAll(orderby: p => p.OrderByDescending(p => p.CreateDate),where:p=>p.CustomerId == int.Parse(customerId));
            }
            if (SearchStatus.HasValue)
            {
                CustomerComment = CustomerComment.Where(p => p.Status == SearchStatus);
            }     
            if (SearchQ != null)
            {
                foreach (var item in SearchQ.ToLower().Split(' '))
                {
                    CustomerComment = CustomerComment.Where(p => p.Name.ToLower().Contains(item)|| p.Family.ToLower().Contains(item) || p.Text.ToLower().Contains(item) || p.Customer.Name.ToLower().Contains(item));
                }
            }
            if (SearchStartDate != null)
            {
                var date = SearchStartDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                CustomerComment = CustomerComment.Where(p => p.CreateDate >= Startdate);
            }
            if (SearchEndDate != null)
            {
                var date = SearchEndDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                CustomerComment = CustomerComment.Where(p => p.CreateDate <= Startdate);
            }
        }
        public ActionResult OnPostStatus(int Id,int Status)
        {
            var CustomerComment = unitofwork.CustomerCommentRepository.GetById(Id);
            CustomerComment.Status = Status;
            if (unitofwork.CustomerCommentRepository.Modifie(CustomerComment))
            {
                if (unitofwork.CustomerCommentRepository.Save())
                {
                    return RedirectToPage("Index");
                }
            }
            return BadRequest();
        }
    }
}

DaliFood.AdminPanel/Pages/Shared/_Sidbar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Shared
{
    public class _SidbarModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

DaliFood.AdminPanel/Pages/Shared/Components/_CommentDetail.cshtml
@model Models.CustomerComment


<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="ModalLabel">نظر @Model.Name @Model.Family برای فروشگاه @Model.Customer.Name</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>@Model.Text</p>
        </div>
        <div class="modal-footer">
            @if (Model.Status == 1)
            {
                <button type="button" class="btn btn-secondary text-white">تایید شده ✔</button>
                <form asp-page-handler="Status" asp-page="/Comment/index" method="post">
                    <input name="Id" type="hidden" value="@Model.Id" />
                    <input name="Status" type="hidden" value="2" />
                    <button type="submit" class="btn btn-danger">رد ✖</button>
                </form>
            }
            else if (Model.Status == 2)
            { <form asp-page-handler="Status" asp-page="/Comment/index" method="post">
                    <input name="Id" type="hidden" value="@Model.Id" />
                    <input name="Status" type="hidden" value="1" />
                    <button type="submit" class="btn btn-success">تایید ✔</button>
                </form>
                <button type="button" class="btn btn-secondary text-white">رد شده ✔</button>
            }
            else
            {
                <form asp-page-handler="Status" asp-page="/Comment/index" method="post">
                    <input name="Id" type="hidden" value="@Model.Id" />
                    <input name="Status" type="hidden" value="1" />
                    <button type="submit" class="btn btn-success">تایید ✔</button>
                </form>
                <form asp-page-handler="Status" asp-page="/Comment/index" method="post">
                    <input name="Id" type="hidden" value="@Model.Id" />
                    <input name="Status" type="hidden" value="2" />
                    <button type="submit" class="btn btn-danger">رد ✖</button>
                </form>
            }
        </div>
    </div>
</div>