DaliFood.AdminPanel/Pages/Financial/Deposit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DaliFood.Utilites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Financial
{
    public class DepositModel : PageModel
    {
        readonly UnitOfWork unitofwork;
        public DepositModel(UnitOfWork unitofwork)
        {
            this.unitofwork = unitofwork;
        }
        [BindProperty]
        public IEnumerable<Models.Deposit> Deposits { get; set; }

        public void OnGet(int? SearchStatus, int? SearchMinPrice, int? SearchMaxPrice, string SearchQ = null, string SearchStartDate = null, string SearchEndDate = null)
        {
            Deposits = unitofwork.DepositRepository.GetAll(orderby: p => p.OrderByDescending(p => p.CreateDate));
            if (SearchStatus.HasValue)
            {
                Deposits = Deposits.Where(p => p.Status == SearchStatus);
            }
            if (SearchMinPrice.HasValue)
            {
                Deposits = Deposits.Where(p => p.Amount >= SearchMinPrice);
            }
            if (SearchMaxPrice.HasValue)
            {
                Deposits = Deposits.Where(p => p.Amount <= SearchMaxPrice);
            }
            if (SearchQ !=null)
            {
                Deposits = Deposits.Where(p => p.Description.Contains(SearchQ) || p.Id.ToString().Contains(SearchQ) || p.UserId.Contains(SearchQ)).Distinct();
            }
            if (SearchStartDate!=null)
            {     
                var date= SearchStartDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year,month,day);
                Deposits = Deposits.Where(p => p.DepositDate >= Startdate);
            }
            if (SearchEndDate != null)
            {
                var date = SearchEndDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                Deposits = Deposits.Where(p => p.DepositDate <= Startdate);
            }

        }
        public ActionResult OnGetConfirm(int Id, int Status)
        {
            var Deposit = unitofwork.DepositRepository.GetById(Id);
            Deposit.Status = Status;
            if (unitofwork.DepositRepository.Modifie(Deposit))
            {
                if (unitofwork.DepositRepository.Save())
                {
                    return RedirectToPage("Deposit");
                }
            }
            return BadRequest();
        }
    }
}

DaliFood.AdminPanel/Pages/Financial/Transaction.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DaliFood.Utilites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Financial
{
    public class TransactionModel : PageModel
    {
        readonly UnitOfWork unitofwork;
        public TransactionModel(UnitOfWork unitofwork)
        {
            this.unitofwork = unitofwork;
        }
        [BindProperty]
        public IEnumerable<Models.Transaction> Transactions { get; set; }

        public void OnGet(int? SearchMinPrice, int? SearchMaxPrice, string SearchQ = null, string SearchStartDate = null, string SearchEndDate = null)
        {
            Transactions = unitofwork.TransactionRepository.GetAll(orderby: p => p.OrderByDescending(p => p.Id));
          
            if (SearchMinPrice.HasValue)
            {
                Transactions = Transactions.Where(p => p.Amount >= SearchMinPrice);
            }
            if (SearchMaxPrice.HasValue)
            {
                Transactions = Transactions.Where(p => p.Amount <= SearchMaxPrice);
            }
            if (SearchQ != null)
            {
                Transactions = Transactions.Where(p => p.Description.Contains(SearchQ) ||p.ItemId.ToString().Contains(SearchQ)||p.Id.ToString().Contains(SearchQ)).Distinct();
            }
            if (SearchStartDate != null)
            {
                var date = SearchStartDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                Transactions = Transactions.Where(p => p.CreateDate >= Startdate);
            }
            if (SearchEndDate != null)
            {
                var date = SearchEndDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                Transactions = Transactions.Where(p => p.CreateDate <= Startdate);
            }
        }
      
      
    }
}

DaliFood.AdminPanel/Pages/Financial/Withdraw.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DaliFood.Utilites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Financial
{
    public class WithdrawModel : PageModel
    {
        readonly UnitOfWork unitofwork;
        public WithdrawModel(UnitOfWork unitofwork)
        {
            this.unitofwork = unitofwork;
        }
        [BindProperty]
        public IEnumerable<Models.Withdraw> Withdraws { get; set; }

        public void OnGet(int? SearchStatus, int? SearchMinPrice, int? SearchMaxPrice, string SearchQ = null, string SearchStartDate = null, string SearchEndDate = null)
        {
            Withdraws = unitofwork.WithdrawRepository.GetAll(orderby: p => p.OrderByDescending(p => p.CreateDate));
            if (SearchStatus.HasValue)
            {
                Withdraws = Withdraws.Where(p => p.Status == SearchStatus);
            }
            if (SearchMinPrice.HasValue)
            {
                Withdraws = Withdraws.Where(p => p.Amount >= SearchMinPrice);
            }
            if (SearchMaxPrice.HasValue)
            {
                Withdraws = Withdraws.Where(p => p.Amount <= SearchMaxPrice);
            }
            if (SearchQ != null)
            {
                Withdraws = Withdraws.Where(p => p.Description.Contains(SearchQ) || p.Id.ToString().Contains(SearchQ) || p.UserId.Contains(SearchQ)).Distinct();
            }
            if (SearchStartDate != null)
            {
                var date = SearchStartDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                Withdraws = Withdraws.Where(p => p.DepositDate >= Startdate);
            }
            if (SearchEndDate != null)
            {
                var date = SearchEndDate.Split('/');
                int year = int.Parse(date[0]);
                int month = int.Parse(date[1]);
                int day = int.Parse(date[2]);
                var Startdate = new DateTime(year, month, day);
                Withdraws = Withdraws.Where(p => p.DepositDate <= Startdate);
            }

        }
        public ActionResult OnGetConfirm(int Id,int Status)
        {
            var Withdraw = unitofwork.WithdrawRepository.GetById(Id);
            Withdraw.Status = Status;
            unitofwork.WithdrawRepository.Modifie(Withdraw);
            unitofwork.WithdrawRepository.Save();
            return RedirectToPage("Withdraw");

        }
    }
}

DaliFood.AdminPanel/Pages/Financial/Deposit.cshtml
@page
@model DaliFood.AdminPanel.Pages.Financial.DepositModel
@{

    ViewData["Title"] = "واریزها";
    ViewData["Section"] = "مدیریت حسابداری";
}

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">لیست واریزی ها</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                @*<a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>*@

            </div>
        </div>
    </div>
    <div class="card-body">

        <form method="get">

            <div class="row">
                <div class="col-md-12">
                    <fieldset>
                        <legend class="font-weight-semibold"><i class="icon-reading mr-2"></i>فیلتر ها </legend>
                        <div class="form-group row">
                            <div class="col-lg-2">
                                <input class="form-control" type="search" name="SearchQ" id="GridSearch" placeholder="متن جست جو" />

                            </div>
                            <div class="col-lg-2">
                                <select class="form-control" name="SearchStatus" id="SearchStatus">
                                    <option value="">وضعیت ها</option>
                                    <option value="0">درحال بررسی</option>
                                    <option value="1">تایید شده</option>
                                    <option value="2">رد شده</option>

                                </select>
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMinPrice" placeholder="حداقل قیمت" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMaxPrice" placeholder="حداکثر قیمت" />
                            </div>

                            <div class="col-lg-2">
                                <input type="text" class="form-control  cursor-pointer" id="enter_date" placeholder="از تاریخ">
                                <input type="text" id="enter_date_1"
                                       aria-label="enter_date" aria-describedby="enter_date" hidden="hidden" />
                                <input class="form-control" type="hidden" name="SearchStartDate" id="enter_date_2"
                                       aria-label="enter_date" aria-describedby="enter_date" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control  cursor-pointer" id="exit_date" placeholder="تا تاریخ">
                                <input type="text" name="exit_date_1" id="exit_date_1" aria-label="exit_date"
                                       aria-describedby="exit_date" hidden="hidden" />
                                <input type="hidden" name="SearchEndDate" id="exit_date_2"
                                       aria-label="exit_date" aria-describedby="exit_date" />
                            </div>

                        </div>

                        <div class="form-group row">
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                                <input type="submit" class="btn btn-default text-info" style="float:left;" value="جستجو!" />
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
            @*<label for="SearchStatus">وضعیت:</label>*@
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">&nbsp;</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">شناسه کاربر</th>
                    <th scope="col">تاریخ واریز</th>

                    <th scope="col">میزان</th>
                    <th scope="col">توضیحات</th>
                    <th scope="col">وضعیت</th>
                    <th scope="col">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Deposits)
                {
                    <tr>
                        <td>@item.UserId</td>
                        <td>@item.DepositDate.ToShamsi()</td>
                        <td>@item.Amount</td>
                        <td>@item.Description</td>
                        @switch (item.Status)
                        {
                            case 0:
                                <td><span class="badge bg-blue">درحال بررسی</span></td>
                                break;
                            case 1:
                                <td><span class="badge bg-success">تایید شده</span></td>
                                break;
                            case 2:
                                <td><span class="badge bg-danger">رد شده</span></td>
                                break;
                            default:
                                <td>-</td>
                                break;
                        }
                        <td>
                            @if (item.Status == 1)
                            {
                                <a class="btn btn-secondary text-white">تاییـد شده ✔</a>
                            }
                            else if (item.Status == 2)
                            {
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="1" onclick="return confirm('آیا از تایید این واریزی مطمئن هستید؟');" class="btn btn-success">تاییـد ✔</a>
                                <a class="btn btn-secondary text-white">رد شده ❌</a>

                            }
                            else
                            {
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="1" onclick="return confirm('آیا از تایید این واریزی مطمئن هستید؟');" class="btn btn-success">تاییـد ✔</a>
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="2" onclick="return confirm('آیا از رد این واریزی مطمئن هستید؟');" class="btn btn-danger">رد ❌</a>
                            }
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $('#enter_date').MdPersianDateTimePicker({
            targetTextSelector: '#enter_date',
            targetDateSelector: '#enter_date_2',
            fromDate: true,
            groupId: 'enter_date',

        });

        $('#exit_date').MdPersianDateTimePicker({
            targetTextSelector: '#exit_date',
            targetDateSelector: '#exit_date_2',
            toDate: true,
            groupId: 'enter_date',

        });
    </script>
}

DaliFood.AdminPanel/Pages/Financial/Transaction.cshtml
@page
@model DaliFood.AdminPanel.Pages.Financial.TransactionModel
@{

    ViewData["Title"] = "تراکنش ها";
    ViewData["Section"] = "مدیریت حسابداری";
}

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">لیست تراکنش ها</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                @*<a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>*@

            </div>
        </div>
    </div>
    <div class="card-body">

        <form method="get">

            <div class="row">
                <div class="col-md-12">
                    <fieldset>
                        <legend class="font-weight-semibold"><i class="icon-reading mr-2"></i>فیلتر ها </legend>
                        <div class="form-group row">
                            <div class="col-lg-2">
                                <input class="form-control" type="search" name="SearchQ" id="GridSearch" placeholder="متن جست جو" />

                            </div>
                            <div class="col-lg-2">
                                <select class="form-control" name="SearchStatus" id="SearchStatus">
                                    <option value="">وضعیت ها</option>
                                    <option value="0">درحال بررسی</option>
                                    <option value="1">تایید شده</option>
                                    <option value="2">رد شده</option>

                                </select>
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMinPrice" placeholder="حداقل قیمت" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMaxPrice" placeholder="حداکثر قیمت" />
                            </div>

                            <div class="col-lg-2">
                                <input class="form-control  cursor-pointer" id="enter_date" placeholder="از تاریخ">
                                <input type="text" id="enter_date_1"
                                       aria-label="enter_date" aria-describedby="enter_date" hidden="hidden" />
                                <input class="form-control" type="hidden" name="SearchStartDate" id="enter_date_2"
                                       aria-label="enter_date" aria-describedby="enter_date" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control  cursor-pointer" id="exit_date" placeholder="تا تاریخ">
                                <input type="text" name="exit_date_1" id="exit_date_1" aria-label="exit_date"
                                       aria-describedby="exit_date" hidden="hidden" />
                                <input type="hidden" name="SearchEndDate" id="exit_date_2"
                                       aria-label="exit_date" aria-describedby="exit_date" />
                            </div>

                        </div>

                        <div class="form-group row">
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                                <input type="submit" class="btn btn-default text-info" style="float:left;" value="جستجو!" />
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
            @*<label for="SearchStatus">وضعیت:</label>*@
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">&nbsp;</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">شناسه کاربر</th>
                    <th scope="col">نوع تراکنش</th>
                    <th scope="col">تاریخ تراکنش</th>

                    <th scope="col">میزان</th>
                    <th scope="col">توضیحات</th>
                    <th scope="col">اعتبار قبلی</th>
                    <th scope="col">اعتبار جدید</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Transactions)
                {
                    <tr>
                        <td>@item.UserId</td>
                        @switch (item.TypeId)
                        {
                            case 0:
                                <td>واریزی</td>
                                break;
                            case 1:
                                <td>برداشت</td>
                                break;
                            case 2:
                                <td>سفارش</td>
                                break;
                            default:
                                <td>-</td>
                                break;
                        }
                        <td>@item.CreateDate.ToShamsi()</td>
                        <td>@item.Amount</td>
                        <td>@item.Description</td>
                        <td>@item.OldAmount</td>
                        <td>@item.NewAmount</td>


                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $('#enter_date').MdPersianDateTimePicker({
            targetTextSelector: '#enter_date',
            targetDateSelector: '#enter_date_2',
            fromDate: true,
            groupId: 'enter_date',

        });

        $('#exit_date').MdPersianDateTimePicker({
            targetTextSelector: '#exit_date',
            targetDateSelector: '#exit_date_2',
            toDate: true,
            groupId: 'enter_date',

        });
    </script>
}

DaliFood.AdminPanel/Pages/Financial/Withdraw.cshtml
@page
@model DaliFood.AdminPanel.Pages.Financial.WithdrawModel
@{

    ViewData["Title"] = "برداشت ها";
    ViewData["Section"] = "مدیریت حسابداری";
}

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">لیست برداشتی ها</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                @*<a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>*@

            </div>
        </div>
    </div>
    <div class="card-body">

        <form method="get">

            <div class="row">
                <div class="col-md-12">
                    <fieldset>
                        <legend class="font-weight-semibold"><i class="icon-reading mr-2"></i>فیلتر ها </legend>
                        <div class="form-group row">
                            <div class="col-lg-2">
                                <input class="form-control" type="search" name="SearchQ" id="GridSearch" placeholder="متن جست جو" />

                            </div>
                            <div class="col-lg-2">
                                <select class="form-control" name="SearchStatus" id="SearchStatus">
                                    <option value="">وضعیت ها</option>
                                    <option value="0">درحال بررسی</option>
                                    <option value="1">تایید شده</option>
                                    <option value="2">رد شده</option>

                                </select>
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMinPrice" placeholder="حداقل قیمت" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control" type="number" name="SearchMaxPrice" placeholder="حداکثر قیمت" />
                            </div>

                            <div class="col-lg-2">
                                <input class="form-control  cursor-pointer" id="enter_date" placeholder="از تاریخ">
                                <input type="text" id="enter_date_1"
                                       aria-label="enter_date" aria-describedby="enter_date" hidden="hidden" />
                                <input class="form-control" type="hidden" name="SearchStartDate" id="enter_date_2"
                                       aria-label="enter_date" aria-describedby="enter_date" />
                            </div>
                            <div class="col-lg-2">
                                <input class="form-control  cursor-pointer" id="exit_date" placeholder="تا تاریخ">
                                <input type="text" name="exit_date_1" id="exit_date_1" aria-label="exit_date"
                                       aria-describedby="exit_date" hidden="hidden" />
                                <input type="hidden" name="SearchEndDate" id="exit_date_2"
                                       aria-label="exit_date" aria-describedby="exit_date" />
                            </div>

                        </div>

                        <div class="form-group row">
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                            </div>
                            <div class="col-lg-3">
                                <input type="submit" class="btn btn-default text-info" style="float:left;" value="جستجو!" />
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
            @*<label for="SearchStatus">وضعیت:</label>*@
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">&nbsp;</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">شناسه کاربر</th>
                    <th scope="col">تاریخ برداشت</th>

                    <th scope="col">میزان</th>
                    <th scope="col">توضیحات</th>

                    <th scope="col">شماره کارت</th>
                    <th scope="col">شماره شبا</th>
                    <th scope="col">کدرهگیری</th>
                    <th scope="col">وضعیت</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Withdraws)
                {
                    <tr>
                        <td>@item.UserId</td>
                        <td>@item.DepositDate.ToShamsi()</td>
                        <td>@item.Amount</td>
                        <td>@item.Description</td>
                        <td>@item.Cardnumber</td>
                        <td>@item.Shabanumber</td>
                        <td>@item.TrackingCode</td>



                        @switch (item.Status)
                        {
                            case 0:
                                <td><span class="badge bg-blue">درحال بررسی</span></td>
                                break;
                            case 1:
                                <td><span class="badge bg-success">تایید شده</span></td>
                                break;
                            case 2:
                                <td><span class="badge bg-danger">رد شده</span></td>
                                break;
                            default:
                                <td>-</td>
                                break;
                        }
                        <td>
                            @if (item.Status == 1)
                            {
                                <a class="btn btn-secondary text-white">تاییـد شده ✔</a>
                            }
                            else if (item.Status == 2)
                            {
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="1" onclick="return confirm('آیا از تایید این برداشت مطمئن هستید؟');" class="btn btn-success">تاییـد ✔</a>
                                <a class="btn btn-secondary text-white">رد شده ❌</a>

                            }
                            else
                            {
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="1" onclick="return confirm('آیا از تایید این برداشت مطمئن هستید؟');" class="btn btn-success">تاییـد ✔</a>
                                <a asp-page-handler="Confirm" asp-route-Id="@item.Id" asp-route-Status="2" onclick="return confirm('آیا از رد این برداشت مطمئن هستید؟');" class="btn btn-danger">رد ❌</a>
                            }
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $('#enter_date').MdPersianDateTimePicker({
            targetTextSelector: '#enter_date',
            targetDateSelector: '#enter_date_2',
            fromDate: true,
            groupId: 'enter_date',

        });

        $('#exit_date').MdPersianDateTimePicker({
            targetTextSelector: '#exit_date',
            targetDateSelector: '#exit_date_2',
            toDate: true,
            groupId: 'enter_date',

        });
    </script>
}