DaliFood.AdminPanel/Pages/Shared/_Sidbar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Shared
{
    public class _SidbarModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

DaliFood.AdminPanel/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DaliFood.AdminPanel.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        public SidebarViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

DaliFood.AdminPanel/Pages/Shared/_Footer.cshtml
<div class="text-center d-lg-none w-100">
    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
        <i class="icon-unfold mr-2"></i>
        Footer
    </button>
</div>

<div class="navbar-collapse collapse" id="navbar-footer">
    <span class="navbar-text">
        &copy; 
        پنل ادمین توسط
        <a href="#" target="_blank">گروه برنامه نویسی اسپاد</a>
    </span>

    <ul class="navbar-nav ml-lg-auto">
        <li class="nav-item"><a href="https://kopyov.ticksy.com/" class="navbar-nav-link" target="_blank"><i class="icon-lifebuoy mr-2"></i> پشتیبانی</a></li>
        <li class="nav-item"><a href="http://demo.interface.club/limitless/docs/" class="navbar-nav-link" target="_blank"><i class="icon-file-text2 mr-2"></i> اطلاعات</a></li>
    </ul>
</div>

DaliFood.AdminPanel/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DaliFood.AdminPanel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-rtl.css" />
    <link href="~/css/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">دالی فود</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                       <partial name="_NavbarPartial" />
                    </ul>
                    <form method="post" asp-page="/Helper"> <input dir="rtl" placeholder="چطور میتونم کمک کنم؟" name="Request"/> </form>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DaliFood.AdminPanel - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.md.bootstrap.datetimepicker.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DaliFood.AdminPanel/Pages/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>

    <!--Grid StyleSheets-->
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet" />

    <!-- Global stylesheets -->
    <link href="~/FarsiFont/FarsiFonts.css" rel="stylesheet" />
    <link href="~/PanelTheme/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" />
    @*<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">*@
    @*<link href="~/Quartsbootstrap.css" rel="stylesheet" />*@
    <link href="~/PanelTheme/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/PanelTheme/assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="~/PanelTheme/assets/css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="~/PanelTheme/assets/css/components.min.css" rel="stylesheet" type="text/css">
    <link href="~/PanelTheme/assets/css/colors.min.css" rel="stylesheet" type="text/css">
    @*<link href="~/persianDatepicker-master/css/persianDatepicker-default.css" rel="stylesheet" />
        <link href="~/persianDatepicker-master/css/fontawesome/css/font-awesome.css" rel="stylesheet" />*@
    <link href="~/PersianDatepicker/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
    <link href="~/css/toastr.min.css" rel="stylesheet" />

    <!--Mvc Grid stylesheets-->
    @* <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet" />*@

    <!-- /global stylesheets -->
    <!-- Core JS files -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- /core JS files -->
    <style>
        .bg-gradient1 {
            background-image: linear-gradient(to right top, #da3a95, #ca3498, #b9309b, #a72e9d, #942d9e, #7e49b8, #5e5ecd, #2471dc, #0099f4, #00bcfb, #00ddf7, #5ffbf1);
        }

        .bg-gradient2 {
            background-image: linear-gradient(to right, #da3a95, #ca3498, #b9309b, #a72e9d, #942d9e, #7e49b8, #5e5ecd, #2471dc, #0099f4, #00bcfb, #00ddf7, #5ffbf1);
        }

        .bg-glass {
            background-color: #ffffff22;
        }
    </style>
</head>
<body>

    <!-- Main navbar -->
    <div class="navbar navbar-expand-md navbar-dark bg-gradient2 navbar-static">
        <partial name="_mainNavbar" />
    </div>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">

        <!-- Main sidebar -->
        @await Component.InvokeAsync("Sidebar")
        @*@await Html.PartialAsync("_mainSidebar")*@
        <!-- /main sidebar -->
        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Page header -->
            <div class="page-header page-header-light">
                <partial name="_pageHeader" />
            </div>
            <!-- /page header -->
            <!-- Content area -->
            <div class="content bg-gradient1">

                @RenderBody()

            </div>
            <!-- /content area -->
            <!-- Footer -->
            <div class="navbar navbar-expand-lg navbar-light">
                <partial name="_Footer" />
            </div>
            <!-- /footer -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->
    <!-- Theme JS files -->
    <script src="~/PanelTheme/global_assets/js/plugins/visualization/d3/d3.min.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/visualization/d3/d3_tooltip.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/forms/styling/switchery.min.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/ui/moment/moment.min.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/pickers/daterangepicker.js"></script>
    <script src="~/Bootbox/bootbox.js"></script>
    <script src="~/PanelTheme/assets/js/app.js"></script>
    <script src="~/PanelTheme/global_assets/js/demo_pages/dashboard.js"></script>
    <script src="~/js/toastr.min.js"></script>

    <script src="~/PanelTheme/global_assets/js/main/bootstrap.bundle.min.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/loaders/blockui.min.js"></script>
    <script src="~/PanelTheme/global_assets/js/plugins/ui/ripple.min.js"></script>
    <script src="~/persianDatepicker-master/js/persianDatepicker.js"></script>
    <!-- /theme JS files -->
    <!--Grid js-->
    <script src="~/PersianDatepicker/jquery.md.bootstrap.datetimepicker.js"></script>
    @*<script src="~/js/mvc-grid/mvc-grid.js"></script>
        <script>
            document.querySelectorAll(".mvc-grid")
                .forEach(element => new MvcGrid(element));
        </script>*@
    @RenderSection("Scripts", required: false)
</body>

</html>

DaliFood.AdminPanel/Pages/Shared/_NavbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    if (await UserManager.IsInRoleAsync(user, SD.ProductEditorRole) || await UserManager.IsInRoleAsync(user, SD.AdminRole))
    {
        <li class="nav-item">
            <a class="nav-link  text-dark" asp-area="" asp-page="/Product/Index">مدیریت غذا ها</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-page="/ProductCategorie/Index">مدیریت دسته بندی ها</a>
        </li>
    }

    if (await UserManager.IsInRoleAsync(user, SD.AdminRole))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-page="/CustomerType/Index">مدیریت انواع فروشنده ها</a>
        </li>
    }
    if (await UserManager.IsInRoleAsync(user, SD.CustomerOwnerRole) || await UserManager.IsInRoleAsync(user, SD.AdminRole))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-page="/CustomersProduct/Index">مدیریت غذای فروشنده ها</a>
        </li>
    }
    if (await UserManager.IsInRoleAsync(user, SD.CustomerOwnerRole))
    {
       
    }
    if (await UserManager.IsInRoleAsync(user, SD.AdminRole))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">افزودن کاربر</a>
        </li>
    }
}

DaliFood.AdminPanel/Pages/Shared/_Sidbar.cshtml
@page
@model DaliFood.AdminPanel.Pages.Shared._SidbarModel
@{
}

DaliFood.AdminPanel/Pages/Shared/_mainNavbar.cshtml
<div class="navbar-brand">
    <a href="index.html" class="d-inline-block">
        <img src="~/PanelTheme/global_assets/images/logo_light.png" alt="">
    </a>
</div>

<div class="d-md-none">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
        <i class="icon-tree5"></i>
    </button>
    <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
        <i class="icon-paragraph-justify3"></i>
    </button>
</div>

<div class="collapse navbar-collapse" id="navbar-mobile">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                <i class="icon-paragraph-justify3"></i>
            </a>
        </li>
    </ul>

    <span class="navbar-text ml-md-3">
        <span class="badge badge-mark border-orange-300 mr-2"></span>
        خوش آمدید مدیر عزیز
    </span>

    <ul class="navbar-nav ml-md-auto">
        @*<li class="nav-item dropdown">
            <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                <i class="icon-make-group mr-2"></i>
                پروفایل اجتماعی
            </a>

            <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                <div class="dropdown-content-body p-2">
                    <div class="row no-gutters">
                        <div class="col-12 col-sm-4">
                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-github4 icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Github</div>
                            </a>

                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-dropbox text-blue-400 icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dropbox</div>
                            </a>
                        </div>

                        <div class="col-12 col-sm-4">
                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-dribbble3 text-pink-400 icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dribbble</div>
                            </a>

                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-google-drive text-success-400 icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Drive</div>
                            </a>
                        </div>

                        <div class="col-12 col-sm-4">
                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-twitter text-info-400 icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Twitter</div>
                            </a>

                            <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                <i class="icon-youtube text-danger icon-2x"></i>
                                <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Youtube</div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </li>*@

        @*<li class="nav-item dropdown">
            <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                <i class="icon-pulse2 mr-2"></i>
                فعالیت ها
            </a>

            <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                <div class="dropdown-content-header">
                    <span class="font-size-sm line-height-sm text-uppercase font-weight-semibold">Latest activity</span>
                    <a href="#" class="text-default"><i class="icon-search4 font-size-base"></i></a>
                </div>

                <div class="dropdown-content-body dropdown-scrollable">
                    <ul class="media-list">
                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-success-400 rounded-round btn-icon"><i class="icon-mention"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
                                <div class="font-size-sm text-muted mt-1">4 minutes ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-pink-400 rounded-round btn-icon"><i class="icon-paperplane"></i></a>
                            </div>

                            <div class="media-body">
                                Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
                                <div class="font-size-sm text-muted mt-1">36 minutes ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-blue rounded-round btn-icon"><i class="icon-plus3"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="#">Chris Arney</a> created a new <span class="font-weight-semibold">Design</span> branch in <span class="font-weight-semibold">Limitless</span> repository
                                <div class="font-size-sm text-muted mt-1">2 hours ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-purple-300 rounded-round btn-icon"><i class="icon-truck"></i></a>
                            </div>

                            <div class="media-body">
                                Shipping cost to the Netherlands has been reduced, database updated
                                <div class="font-size-sm text-muted mt-1">Feb 8, 11:30</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-warning-400 rounded-round btn-icon"><i class="icon-comment"></i></a>
                            </div>

                            <div class="media-body">
                                New review received on <a href="#">Server side integration</a> services
                                <div class="font-size-sm text-muted mt-1">Feb 2, 10:20</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="mr-3">
                                <a href="#" class="btn bg-teal-400 rounded-round btn-icon"><i class="icon-spinner11"></i></a>
                            </div>

                            <div class="media-body">
                                <strong>January, 2018</strong> - 1320 new users, 3284 orders, $49,390 revenue
                                <div class="font-size-sm text-muted mt-1">Feb 1, 05:46</div>
                            </div>
                        </li>
                    </ul>
                </div>

                <div class="dropdown-content-footer bg-light">
                    <a href="#" class="font-size-sm line-height-sm text-uppercase font-weight-semibold text-grey mr-auto">All activity</a>
                    <div>
                        <a href="#" class="text-grey" data-popup="tooltip" title="Clear list"><i class="icon-checkmark3"></i></a>
                        <a href="#" class="text-grey ml-2" data-popup="tooltip" title="Settings"><i class="icon-gear"></i></a>
                    </div>
                </div>
            </div>
        </li>*@

        <li class="nav-item">
            <a href="#" class="navbar-nav-link">
                <i class="icon-switch2"></i>
                <span class="d-md-none ml-2">Logout</span>
            </a>
        </li>
    </ul>
</div>

DaliFood.AdminPanel/Pages/Shared/_mainSidebar.cshtml
<div class="sidebar sidebar-light sidebar-main sidebar-expand-md">
    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-right8"></i>
        </a>
        <span class="font-weight-semibold">Navigation</span>
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->
    <!-- Sidebar content -->
    <div class="sidebar-content">
        <!-- User menu -->
        <div class="sidebar-user-material">
            <div class="sidebar-user-material-body">
                <div class="card-body text-center">
                    <a href="#">
                        <img src="~/PanelTheme/global_assets/images/demo/users/user-icon.jpg" class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
                    </a>
                    <h6 class="mb-0 text-white text-shadow-dark">کاربر جاری</h6>
                    <span class="font-size-sm text-white text-shadow-dark">خوش آمدید</span>
                </div>

                <div class="sidebar-user-material-footer">
                    <a href="#user-nav" class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle" data-toggle="collapse"><span>حساب کاربری من</span></a>
                </div>
            </div>

            <div class="collapse" id="user-nav">
                <ul class="nav nav-sidebar">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-user-plus"></i>
                            <span>پروفایل</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-coins"></i>
                            <span>گزارشات</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-comment-discussion"></i>
                            <span>پیام ها</span>
                            <span class="badge bg-teal-400 badge-pill align-self-center ml-auto">58</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-cog5"></i>
                            <span>تنظیمات</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-switch2"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /user menu -->
        <!-- Main navigation -->

        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">
                <!-- Main -->

                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link active">
                        <i class="icon-home4 text-success"></i>
                        <span>
                            خانه
                        </span>
                    </a>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link">
                        <i class="icon-equalizer"></i><span>مدیریت تنظیمات</span>
                    </a>
                    <ul class="nav nav-group-sub">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Setting" asp-action="Update" class="nav-link">
                                تنظیمات
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="ImageSetting" asp-action="Update" class="nav-link">
                                تنظیمات عکس
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link">
                        <i class="icon-drawer3"></i> <span>مدیریت محتوا</span>
                    </a>
                    <ul class="nav nav-group-sub">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="NewsCategory" asp-action="Index" class="nav-link active">
                                گروه بندی اخبار
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="News" asp-action="Index" class="nav-link">
                                اخبار
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="BlogCategory" asp-action="Index" class="nav-link">
                                گروه بندی وبلاگ
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Blog" asp-action="Index" class="nav-link">
                                وبلاگ
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Slider" asp-action="Index" class="nav-link">
                                اسلایدر
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-action="Index" asp-controller="Video" class="nav-link">
                                ویدیو
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="nav-link">
                                برند
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Rule" asp-action="Update" class="nav-link">
                                قوانین و مقررات
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="FAQ" asp-action="Index" class="nav-link">
                                سوالات متداول
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link">
                        <i class="icon-store"></i>
                        <span>مدیریت محصولات</span>
                    </a>
                    <ul class="nav nav-group-sub">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="ProductCategory" asp-action="Index" class="nav-link">
                                گروه بندی محصولات
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link">
                                محصولات
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Discount" asp-action="Index" class="nav-link">
                                تخفیفات
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link active">
                        <i class="icon-exit3 text-danger"></i>
                        <span>
                            ویترین
                        </span>
                    </a>
                </li>

            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->
</div>

DaliFood.AdminPanel/Pages/Shared/_pageHeader.cshtml
<div class="page-header-content header-elements-md-inline">
    <div class="page-title d-flex">
        <h4>
            <i class="icon-arrow-right6 mr-2"></i>
            <span class="font-weight-semibold">
                @ViewData["Section"]
            </span>
            - @ViewData["Title"]
        </h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>

    @*<div class="header-elements d-none">
        <div class="d-flex justify-content-center">
            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                <i class="icon-bars-alt text-pink-300"></i>
                <span>آمارها</span>
            </a>
            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                <i class="icon-calculator text-pink-300"></i>
                <span>حسابداری</span>
            </a>
            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                <i class="icon-calendar5 text-pink-300"></i>
                <span>تقویم</span>
            </a>
        </div>
    </div>*@
</div>

<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="index.html" class="breadcrumb-item">
                <i class="icon-home2 mr-2"></i>
                @ViewData["Section"]
            </a>
            <span class="breadcrumb-item active">
                @ViewData["Title"]
            </span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>

    <div class="header-elements d-none">
        <div class="breadcrumb justify-content-center">
            @*<a href="#" class="breadcrumb-elements-item">
                <i class="icon-comment-discussion mr-2"></i>
                پشتیبانی
            </a>*@

            @*<div class="breadcrumb-elements-item dropdown p-0">
                <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear mr-2"></i>
                    تنظیمات
                </a>

                <div class="dropdown-menu">
                    <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                    <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                    <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                </div>
            </div>*@
        </div>
    </div>
</div>