DaliFood.AdminPanel/Pages/Letter/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DaliFood.AdminPanel.Helpers;
using DaliFood.Models.Data;
using DaliFood.Utilites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaliFood.AdminPanel.Pages.Letter
{
    public class IndexModel : PageModel
    {
        readonly UnitOfWork unitofwork;
        private readonly ApplicationDbContext context;

        public IndexModel(UnitOfWork unitofwork, ApplicationDbContext context)
        {
            this.unitofwork = unitofwork;
            this.context = context;
        }

        
        [BindProperty]
        public IEnumerable<Models.Letter> Letters { get; set; }
        
        
        public void OnGet()
        {
            Letters = unitofwork.LetterRepository.GetAll();
        }

        public async Task<ActionResult> OnGetDelete(int Id)
        {
            var entity = context.Letters.Find(Id);
            if (entity == null)
                return NotFound();
            context.Letters.Remove(entity);
            await context.SaveChangesAsync();

            var products = unitofwork.ProductRepository.GetAll(where: p => p.CategorieId == Id);
            foreach (var item in products)
            {
                unitofwork.ProductRepository.Delete(item);
            }
            unitofwork.ProductRepository.Save();
            unitofwork.CustomerTypeRepository.Save();
            return RedirectToPage("Index");
        }

    }
}

DaliFood.AdminPanel/Pages/Letter/Index.cshtml
@page
@model DaliFood.AdminPanel.Pages.Letter.IndexModel
@{
    ViewData["Title"] = "لیست";
    ViewData["Section"] = "مدیریت پیام ها";
}

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">لیست پیام ها</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                @*<a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                    <input class="form-control" type="search" id="GridSearch" placeholder="جست و جو" />*@
            </div>
        </div>
    </div>
    <div class="card-body">
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">نام و نام خانوادگی</th>
                    <th scope="col">ایمیل</th>
                    <th scope="col">پیام</th>
                    <th scope="col">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Letters)
                {
                    <tr>
                        <td>@item.FullName.</td>
                        <td>@item.Email</td>
                        <td>@item.Message</td>
                        <td>
@*                            <a asp-page="upsert" asp-route-Id="@item.Id" class="btn btn-info">پاسخ</a>*@
                            <a asp-page-handler="Delete"  asp-route-Id="@item.Id" onclick="return confirm('آیا از حذف این پیام مطمئن هستید؟');" class="btn btn-danger">حذف</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>